### ISSUE TITLE
libfsxfs_inode_get_number_of_attributes_extents: unable to retrieve number of attributes entries.

### ISSUE THREAD

**Issue by sydp** [libyal/libfsxfs#6]
Currently working on a PR in the dfVFS repository and encountered the following error:

```
ERROR: testFileEntryExistsByPathSpec (vfs.overlay_file_system.OverlayFileSystemTestWithXFS)
Test the file entry exists by path specification functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/dfvfs/dfvfs/tests/vfs/overlay_file_system.py", line 191, in testFileEntryExistsByPathSpec
    self.assertFalse(file_system.FileEntryExistsByPathSpec(path_spec))
  File "./dfvfs/vfs/overlay_file_system.py", line 82, in FileEntryExistsByPathSpec
    return self.GetFileEntryByPathSpec(path_spec)
  File "./dfvfs/vfs/overlay_file_system.py", line 106, in GetFileEntryByPathSpec
    for entry in overlay_dir.entries:
  File "./dfvfs/vfs/overlay_directory.py", line 118, in _EntriesGenerator
    yield from self._ReadDirectory(location)
  File "./dfvfs/vfs/overlay_directory.py", line 58, in _ReadDirectory
    for attribute in layer_file_entry.attributes:
  File "./dfvfs/vfs/file_entry.py", line 198, in attributes
    return self._GetAttributes()
  File "./dfvfs/vfs/xfs_file_entry.py", line 87, in _GetAttributes
    self._fsxfs_file_entry.extended_attributes):
OSError: pyfsxfs_file_entry_get_extended_attributes: unable to retrieve number of extended attributes.
libcdata_array_get_number_of_entries: invalid array.
libfsxfs_inode_get_number_of_attributes_extents: unable to retrieve number of attributes entries.
libfsxfs_attributes_get_from_block: unable to retrieve number of attributes extents.
libfsxfs_attributes_get_from_inode: unable to retrieve extended attributes from attributes block: 0.
libfsxfs_internal_file_entry_get_extended_attributes: unable to retrieve extended attributes from inode.
libfsxfs_file_entry_get_number_of_extended_attributes: unable to determine extended attributes.

======================================================================
ERROR: testGetFileEntryByPathSpec (vfs.overlay_file_system.OverlayFileSystemTestWithXFS)
Tests the GetFileEntryByPathSpec function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/dfvfs/dfvfs/tests/vfs/overlay_file_system.py", line 232, in testGetFileEntryByPathSpec
    file_entry = file_system.GetFileEntryByPathSpec(path_spec)
  File "./dfvfs/vfs/overlay_file_system.py", line 106, in GetFileEntryByPathSpec
    for entry in overlay_dir.entries:
  File "./dfvfs/vfs/overlay_directory.py", line 118, in _EntriesGenerator
    yield from self._ReadDirectory(location)
  File "./dfvfs/vfs/overlay_directory.py", line 58, in _ReadDirectory
    for attribute in layer_file_entry.attributes:
  File "./dfvfs/vfs/file_entry.py", line 198, in attributes
    return self._GetAttributes()
  File "./dfvfs/vfs/xfs_file_entry.py", line 87, in _GetAttributes
    self._fsxfs_file_entry.extended_attributes):
OSError: pyfsxfs_file_entry_get_extended_attributes: unable to retrieve number of extended attributes. libcdata_array_get_number_of_entries: invalid array. libfsxfs_inode_get_number_of_attributes_extents: unable to retrieve number of attributes entries. libfsxfs_attributes_get_from_block: unable to retrieve number of attributes extents. libfsxfs_attributes_get_from_inode: unable to retrieve extended attributes from attributes block: 0. libfsxfs_internal_file_entry_get_extended_attributes: unable to retrieve extended attributes from inode. libfsxfs_file_entry_get_number_of_extended_attributes: unable to determine extended attributes.
```

Possibly related to https://github.com/libyal/libfsxfs/issues/3?

The source XFS image is here https://github.com/log2timeline/dfvfs/pull/659/files#diff-ad5c1a9ddcdc8ae619be746480eb0e30026239525a89a901297e848116663e41 and was generated with this: https://github.com/dfirlabs/overlayfs-specimens

**Comment by joachimmetz** [comment]
```
fsxfsinfo -F '/overlay' overlay_xfs.dd 
fsxfsinfo 20220528

X File System information:

File entry:
	Path			: /overlay
	Inode number		: 11077
	Size			: 0
	Modification time	: 2022-04-22T12:00:26.413114484Z
	Inode change time	: 2022-04-22T12:00:26.413114484Z
	Access time		: 2022-04-22T12:00:26.441113454Z
	Creation time		: 2022-04-22T12:00:26.413114484Z
	Number of links		: 2
	Owner identifier	: 0
	Group identifier	: 0
	File mode		: drwxr-xr-x (0040755)
Unable to print file entry information.
libcdata_array_get_number_of_entries: invalid array.
libfsxfs_inode_get_number_of_attributes_extents: unable to retrieve number of attributes entries.
libfsxfs_attributes_get_from_block: unable to retrieve number of attributes extents.
libfsxfs_attributes_get_from_inode: unable to retrieve extended attributes from attributes block: 0.
libfsxfs_internal_file_entry_get_extended_attributes: unable to retrieve extended attributes from inode.
libfsxfs_file_entry_get_number_of_extended_attributes: unable to determine extended attributes.
info_handle_file_entry_value_with_name_fprint: unable to retrieve number of extended attributes.
info_handle_file_entry_fprint_by_path: unable to print file entry.
```

Looks like the inode has an attribute fork but it is empty

```
libfsxfs_inode_read_data: number of attributes extents                  : 0
libfsxfs_inode_read_data: attributes fork offset                        : 0 (0)
libfsxfs_inode_read_data: attributes fork type                          : 2 (XFS_DINODE_FMT_EXTENTS)
```

**Comment by joachimmetz** [comment]
> Possibly related to https://github.com/libyal/libfsxfs/issues/3?

looks more like an unsupported format edge case with extent based extended attributes

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libfsxfs/commit/6ed7893f5b49592df614bcce8ba80693d78fdfc0
